---
trigger: weekly_sync # <-- 👋 pick a trigger
title: Weekly Sync   # <-- 👋 pick a title
surfaces:
  - issue
#   - pull_request
#   - discussions
description: Submit your weekly sync update

# Each command has one or more steps. You can add up to 25 steps.
steps:
  # This displays a menu, similar to typing `@`.
  - type: menu
    id: weekly_feels
    label: How have you been this week?
    options:
      - ":smiley:"
      - ":slightly_smiling_face:"
      - ":neutral_face:"
      - ":slightly_frowning_face:"
      - ":frowning_face:"

  # This displays a form with a dropdown, text input, and markdown editor.
  - type: form
    style: modal
    body:
      - type: dropdown
        attributes:
          label: Priority
          options:
          - label: "🟢 Normal"
          - label: "⚠️ Important"
          - label: "💥 Emergency"
      - type: input
        attributes:
          label: Name
          format: text
      - type: textarea
        attributes:
          label: Message
          placeholder: What happened?
  # You can use slash commands to run GitHub Actions using repository_dispatch.
  # Any input provided to menus or forms will be available from your workflow.
  # - type: repository_dispatch
  #   eventType: special_merge
  # You can insert markdown into the markdown editor. The template property is
  # processed as a Liquid template.
  - type: fill
    template: |-
      Thank you for creating a slash command! See
      Here is the data you provided: {{data}}
      And here is some information about the command: {{command}}
