# This is a basic workflow to help you get started with Actions

name: Issue Bot Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_issue:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Scheduled Issue
        uses: imjohnbo/issue-bot@2.4.1
        with:
          title: Scheduled Issue Test
