name: Weekly Tracker
on:
  workflow_dispatch:
  
jobs:
  daily_standup:
    name: Weekly Tracker
    runs-on: ubuntu-latest
    steps:
    
    - name: issue-bot
      uses: imjohnbo/issue-bot@fix/2.4.2
      with:
        close-previous: true
        template: ".github/ISSUE_TEMPLATE/this-week.md" # assignees, labels will be overridden if present in YAML header
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
