name: Assign Milestone

on:
  issues:
    types: [opened]
    
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context.issue.number)
