name: Assign Milestone

on:
  issues:
    types: [opened]
    
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/github-script@v7.0.1
        with:
          script: |
            console.log(context.issue.number)
