name: Assign Milestone

on:
  issues:
    types: [opened]
    
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          script: |
            console.log(github.issues.issue_number)
