name: Limit Repo Interactions

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  limitInteractions:
    runs-on: ubuntu-latest
    steps:
    - uses: octokit/request-action@v2.0.0
      id: limit
      with:
        route: PUT /repos/:owner/:repo/interaction-limits
        owner: ${{ github.owner }}
        repository: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: echo Setting interaction limits
