name: Get Rate Limit

on: workflow_dispatch

jobs:
  get-rate-limit:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get Rate Limit using REST API
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/rate_limit
      - name: Get the authenticated user
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/user
        
