on: workflow_dispatch


jobs:
  funstuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: '12'
      - run: npm install
      - run: npm test
