on: workflow_dispatch


jobs:
  funstuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: '12'
      - run: npm install
      - run: npm test
