on: workflow_dispatch


jobs:
  funstuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: '12'
      - run: npm install
      - run: npm test
