name: Tallzeebaa Testing

on: workflow_dispatch

jobs:
  tallzeebaa-testing:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
      - name: Ticket 2938514
        run: |
          cd ${{ github.workspace }}
          echo "Current directory is $(pwd)"
          ls -la
          git_version=$(git --version)
          echo "Git version: $git_version"
          git_tags=$(git tag -l)
          echo "Git tags: $git_tags"
          git_branches=$(git branch)
          echo "Git branches: $git_branches"
