name: Tallzeebaa Testing

on: workflow_dispatch

jobs:
  tallzeebaa-testing:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
      - name: Ticket 2938514
        run: |
          cd ${{ github.workspace }}
          echo "Current directory is $(pwd)"
          ls -la
          git_version=$(git --version)
          echo "Git version: $git_version"
          echo "Fetching tags..."
          git fetch --tags
          
          echo "Listing tags:"
          git tag -l | tee git_tags.txt
          echo "Git tags:"
          cat git_tags.txt
          
          echo "Listing branches:"
          git branch -a | tee git_branches.txt
          echo "Git branches:"
          cat git_branches.txt
