name: Tallzeebaa Testing

on: workflow_dispatch

jobs:
  tallzeebaa-testing:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
      - name: Ticket 2938514
        run: |
          cd ${{ github.workspace }}
          echo "Current directory is $(pwd)"
          ls -la
          test=$(git --version)
          echo "$test"
          test2=$(git tag -l)
          echo "$test2"
          test3=$(git branch)
          echo "$test3"
